language: python
env:
- TOXENV=py27
install: pip install tox --use-mirrors
script: tox
deploy:
  provider: pypi
  user: ivanlei
  password:
    secure: Dgkqln/66oNEvEgfxmXAUFCpsAWR7Pwk/BuplCLEKMXKV7kXox2cy5laWcCjJs/PPv/l+3ytj9HQEZAscUCFJNSNiCUr5/0JtX5o8vo1NTRwYTticxeQt3x9JuzD2PvJisxuMia7RZe7WGbHXzuIzz9qClk60DCY340dIRR7iyE=
  on:
    tags: true
    repo: ivanlei/threatbutt
